ktor:
    application:
        modules:
            - com.shoppinglist.ApplicationKt.module
    deployment:
        port: 8080
db:
    url: "jdbc:postgresql://localhost:5432/postgres"
    user: "postgres"
    pass: ""